config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :dogs
  resources :locations
  resources :admins
  resources :bookings

  root 'dogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :locations
  has_one :user
end

app/models/breed.rb
class Breed < ApplicationRecord
  belongs_to :dogs

  def api
    require 'open-uri'
    require 'json'

    result = JSON.parse(open("https://api.thedogapi.com/v1/breeds?api_key=d1131aa2-3782-4d20-9f37-").read)

    result.each do |key|
      breed = Breed.new
      breed.name = "#{key['name']}"
      breed.weight = "#{key['weight']['metric']}"
      breed.save
    end
  end

  def average_weight
    Breed.all.each do |breed|
      one = breed.weight.split(' - ')[0]
      two = breed.weight.split(' - ')[1]
      avg = (one.to_i + two.to_i) / 2
    end

    Dog.all.each do |dog|
      dog.update_all(size: "small") if avg === (1..10)
      dog.update_all(size: "medium") if avg === (11..40)
      dog.update_all(size: "large") if avg === (41..150)
      dog.save
    end
  end
end

app/models/capacity.rb
class Capacity < ApplicationRecord
  belongs_to :locations
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_one :breeds
  belongs_to :user
  has_many_attached :images
  has_many_attached :records

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/models/location.rb
class Location < ApplicationRecord

  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :dogs
  has_many :bookings
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    @dog = Dog.all
    if params[:search]
      @dog = Dog.search(params[:search]).order("name ASC")
    else
      @dog = Dog.all.order("name ASC")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(bookings_params)
    @booking.save!
    redirect_to dogs_path
  end

  private

  def bookings_params
    params.require(:booking).permit(:date, :dogs_id, :locations_id)
  end


end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def new
    @dog = Dog.new
  end

  def create
    @dog = current_user.dogs.create(dog_params.merge(user_id: current_user.id))
    @dog.images.attach(params[:dog][:images])
    @dog.records.attach(params[:dog][:records])
    @dog.save!
    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :approved, :breeds_id, records: [], images: [])
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @location = Location.all
  end

  def show
    @location = Location.find(params[:id])
  end

  def update
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.images.attach(params[:location][:images])
    @location.save!
    redirect_to dogs_path
  end

  private

  def location_params
    params.require(:location).permit(:name, :description, :small, :medium, :large, images: [])
  end



end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :phone, :address])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name,
                                                              :first_name,
                                                              :phone,
                                                              :address])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<h1>Admin List</h1>

<div>
  <%= form_tag admins_path, :method => "get" do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Dogs" %>
    <%= submit_tag "Search" %>
  <% end %>
</div>



<div>
  <% @dog.each do |dog| %>
    <%= dog.name %><br>
    <% dog.records.each do |records|  %>
      - <%= records.name %><br>
    <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Dog Booking Form</h1>

<%= form_with model: @booking, local: true do |f| %>
  <%= f.label :dogs %>
  <%= f.collection_select :dogs_id, current_user.dogs.order(:name), :id, :name %><br>

  <%= f.label :locations %>
  <%= f.collection_select :locations_id, Location.order(:name), :id, :name %><br>

  <%= f.label :date %>
  <%= f.date_select :date, :order => [:day, :month, :year] %><br>

  <%= f.submit 'Submit' %>
<% end %>

app/views/dogs/index.html.erb
<h1>Homepage</h1>

app/views/dogs/new.html.erb
<h1>Dog Registration Form</h1>

<%= form_with model: @dog, local: true do |f| %>

  <%= f.label :name, "Dog Name"  %>
  <%= f.text_field :name %><br>

  <%= f.label :breeds, "Breed" %>
  <%= f.collection_select :breeds_id, Breed.order(:name), :id, :name %><br>

  <%= f.label :images, "Photo" %>
  <%= f.file_field :images, multiple: true %><br>

  <%= f.label :records, "Vet Records" %>
  <%= f.file_field :records, multiple: true  %><br>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogDaycare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li>
        <%= link_to "Home", dogs_path %>
      </li>
      <li>
        <%= link_to "New Dog", new_dog_path %>
      </li>
      <li>
        <%= link_to "New Location", new_location_path %>
      </li>
      <li>
        <%= link_to "New Booking", new_booking_path %>
      </li>
      <li>
        <%= link_to "Admin", admins_path %>
      </li>
    </ul>

    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<% @location.each do |location| %>
  <%= location.name %>
  <%= location.description %>
    <% location.images.each do |image| %>
      <%= image_tag image %>
    <% end %>
<% end %>

app/views/locations/new.html.erb
<h1>New Location Form</h1>

<%= form_with model: @location, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :description %>
  <%= f.text_area :description %><br><br>

  <%= f.label :small %><br>
  <%= f.number_field :small %><br>

  <%= f.label :medium %><br>
  <%= f.number_field :medium %><br>

  <%= f.label :large %><br>
  <%= f.number_field :large %><br>

  <%= f.label :images, "Photos" %>
  <%= f.file_field :images, multiple: true  %><br>

  <%= f.submit 'Submit' %>
<% end %>

app/views/locations/show.html.erb
<% @location.images.each do |image| %>
  <%= image_tag image %>
<% end %>